<a href="https://colab.research.google.com/github/IgorMatias04/AulasIA03/blob/main/AulaIA03_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np


In [3]:
k1 = np.array([1, 4, 9, 16, 25, 36])
print(np.sqrt(k1))

print(np.exp(k1))

[1. 2. 3. 4. 5. 6.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10 4.31123155e+15]


In [4]:
l = np.array([[4, 5], [6, 1], [7, 4]])
print(l)

l_linha_1 = l[0, :]
print(l_linha_1)

l_linha_2 = l[1, :]
print(l_linha_2)

l_linha_3 = l[2, :]
print(l_linha_3)

l_coluna_1 = l[:, 0]
print(l_coluna_1)

l_coluna_2 = l[:, 1]
print(l_coluna_2)

[[4 5]
 [6 1]
 [7 4]]
[4 5]
[6 1]
[7 4]
[4 6 7]
[5 1 4]


In [5]:
m = np.array([1, 2, 3, 4, 5, 6])
print(m[1])

print(m[0:2])

print(m[1:])

print(m[-3:])

2
[1 2]
[2 3 4 5 6]
[4 5 6]


In [6]:
n = np.array([[1, 2], [3, 4]])
o = np.array([[1, 1], [1, 1]])
res1 = n+o
print(res1)

res2 = n*o
print(res2)

[[2 3]
 [4 5]]
[[1 2]
 [3 4]]


In [7]:
p = np.array([[1, 2], [3, 4], [5, 6]])
q = np.array([[2, 1]])
print(p+q)

[[3 3]
 [5 5]
 [7 7]]


In [8]:
r = np.arange(15).reshape((3, 5))

print(r)

s = r.T
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [9]:
r = np.arange(15).reshape((3, 5))

print(r)

s = r.transpose((1,0))
print(s)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [10]:
t = np.arange(16).reshape((2, 2, 4))
print(t)

u = t.transpose((1, 0, 2))
print(u)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [11]:
t = np.arange(16).reshape((2, 2, 4))
print(t)
u = t.swapaxes(1, 2)
print(u)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]
[[[ 0  4]
  [ 1  5]
  [ 2  6]
  [ 3  7]]

 [[ 8 12]
  [ 9 13]
  [10 14]
  [11 15]]]


In [12]:
v = np.random.randn(4, 4)
print(v)

x = (v > 0)
print(x)

z = np.where(x > 0, 1, -1)
print(z)

[[ 0.3021981   0.66746807  0.25711752 -1.07216109]
 [ 0.06495    -1.3233864   1.50503498  1.38759492]
 [-0.57443898  0.72738515 -0.07124843  1.09856788]
 [ 0.77818822  1.95127307  0.17771786  0.5708104 ]]
[[ True  True  True False]
 [ True False  True  True]
 [False  True False  True]
 [ True  True  True  True]]
[[ 1  1  1 -1]
 [ 1 -1  1  1]
 [-1  1 -1  1]
 [ 1  1  1  1]]
