<a href="https://colab.research.google.com/github/IgorMatias04/AulasIA03/blob/main/AulaIA03_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
c = np.empty([3,2], dtype = int)
print(c)

[[56385424        0]
 [       0        0]
 [       0        0]]


In [6]:
d = np.zeros([4,3])
print(d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
e= np.ones([5,7])
print(e)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [8]:
f = np.eye(5)
print(f)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
g = np.random.random ((5))
print(g)

[0.41651069 0.66255057 0.33289506 0.11795843 0.91205241]


In [10]:
g2 = np.random.randn ((5))
print(g2)

[ 0.90570867 -0.53968636 -0.7544409   0.93546498 -0.40483291]


In [11]:
h = np.floor(10*np.random.random ((3,4)))
print(h)
h = (10*np.random.random((3,4)))
print(h)
h = np.floor(h)
print(h)

[[2. 3. 4. 2.]
 [8. 3. 9. 5.]
 [9. 8. 7. 5.]]
[[4.54552441 7.32750288 7.62923199 5.75968685]
 [7.55310012 7.77124481 3.89179377 0.77510007]
 [8.48501185 3.26442603 7.76264663 6.94041612]]
[[4. 7. 7. 5.]
 [7. 7. 3. 0.]
 [8. 3. 7. 6.]]


In [12]:
gnr = np.random.default_rng(0)
i = gnr.random(3)
print (i)

[0.63696169 0.26978671 0.04097352]


In [13]:
i = gnr.integers(10, size=(3, 4))
print(i)

[[0 0 1 8]
 [6 9 5 6]
 [9 7 6 5]]


In [14]:
j = np.array([11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 18, 19, 20])
j = np.unique(j)
print(j)

[11 12 13 14 15 16 17 18 19 20]


In [15]:
k = np.array([[17,22,43],[27,25,14],[15,24,32]])
print(k)

print(k[0][1])

print(k.shape)

print(k.max())

print(k.min())

print((k.sum()))

print(k.mean())

print(k.std())

[[17 22 43]
 [27 25 14]
 [15 24 32]]
22
(3, 3)
43
14
219
24.333333333333332
8.615231988880057
