<a href="https://colab.research.google.com/github/IgorMatias04/AulasIA03/blob/main/AulaIA3_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([12,34,26,18,10])

print(a)
print(a.dtype)

[12 34 26 18 10]
int64


In [3]:
a1 = np.array([1, 2, 3], dtype = np.float64)

print(a1)
print(a1.dtype)
a2 = np.array([1, 2, 3], dtype = np.int32)

print(a2)
print(a2.dtype)

[1. 2. 3.]
float64
[1 2 3]
int32


In [4]:
a3 = np.array([1.4, 3.6, -5.1, 9.42, 4.999999])

print(a3)
print(a3.dtype)

a4 = a3.astype(np.int32)

print(a4)
print(a4.dtype)

a5 = np.array([1, 2, 3, 4])
print(a5)
print(a5.dtype)
a6 = a5.astype(float)

print(a6)
print(a6.dtype)

[ 1.4       3.6      -5.1       9.42      4.999999]
float64
[ 1  3 -5  9  4]
int32
[1 2 3 4]
int64
[1. 2. 3. 4.]
float64


In [5]:
b = np.array([[7,2,23],[12,27,4],[5,34,23]])

print(b)

[[ 7  2 23]
 [12 27  4]
 [ 5 34 23]]
